(function(){
  const state={busy:0};
  function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function ensure(){
    if(!document.getElementById('lola-toast-stack')){const x=document.createElement('div');x.id='lola-toast-stack';x.className='lola-toast-stack';x.setAttribute('aria-live','polite');document.body.appendChild(x)}
    if(!document.getElementById('lola-progress')){const x=document.createElement('div');x.id='lola-progress';x.className='lola-progress';document.body.appendChild(x)}
    if(!document.getElementById('lola-offline')){const x=document.createElement('div');x.id='lola-offline';x.className='lola-offline';x.textContent='Connection lost — changes will not be submitted.';document.body.appendChild(x)}
  }
  function dismiss(el){el.classList.remove('show');setTimeout(()=>el.remove(),240)}
  function toast(message,{type='success',duration=3200,action=null}={}){ensure();const el=document.createElement('div');el.className='lola-toast '+type;el.innerHTML=`<div class="lola-toast-mark"></div><div class="lola-toast-copy">${escapeHtml(message)}</div>${action?`<button>${escapeHtml(action.label)}</button>`:''}`;document.getElementById('lola-toast-stack').appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));if(action)el.querySelector('button').onclick=()=>{action.onClick?.();dismiss(el)};const timer=setTimeout(()=>dismiss(el),duration);el.onmouseenter=()=>clearTimeout(timer);return el}
  function busy(on=true){ensure();state.busy=Math.max(0,state.busy+(on?1:-1));document.getElementById('lola-progress').classList.toggle('active',state.busy>0);document.documentElement.classList.toggle('lola-busy',state.busy>0)}
  async function run(task,{success,error='Something went wrong.',button=null}={}){const old=button?.innerHTML;if(button){button.disabled=true;button.classList.add('is-loading');button.innerHTML='<span class="lola-spinner"></span><span>Working</span>'}busy(true);try{const result=await task();if(success)toast(typeof success==='function'?success(result):success);return result}catch(e){toast(e?.message||error,{type:'error',duration:5200});throw e}finally{busy(false);if(button){button.disabled=false;button.classList.remove('is-loading');button.innerHTML=old}}}
  function confirm({title='Confirm action',message='',confirmLabel='Confirm',danger=false}={}){return new Promise(resolve=>{const layer=document.createElement('div');layer.className='lola-dialog-layer';layer.innerHTML=`<div class="lola-dialog" role="dialog" aria-modal="true"><div class="lola-dialog-kicker">LOLA DESK</div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(message)}</p><div class="lola-dialog-actions"><button class="btn btn-ghost" data-no>Cancel</button><button class="btn ${danger?'lola-danger':'btn-primary'}" data-yes>${escapeHtml(confirmLabel)}</button></div></div>`;document.body.appendChild(layer);requestAnimationFrame(()=>layer.classList.add('show'));const done=v=>{layer.classList.remove('show');setTimeout(()=>layer.remove(),220);resolve(v)};layer.querySelector('[data-no]').onclick=()=>done(false);layer.querySelector('[data-yes]').onclick=()=>done(true);layer.onclick=e=>{if(e.target===layer)done(false)};layer.querySelector('[data-yes]').focus()})}
  function skeleton(root,rows=3){root.innerHTML=Array.from({length:rows},()=>'<div class="lola-skeleton"><i></i><span></span><em></em></div>').join('')}
  function connectivity(){ensure();const sync=()=>document.getElementById('lola-offline').classList.toggle('show',!navigator.onLine);addEventListener('online',()=>{sync();toast('Connection restored.')});addEventListener('offline',sync);sync()}
  function commandPalette(){const actions=[['Open Home','dashboard.html'],['Open Operations','operations-os.html'],['Open Growth','growth-os.html'],['Open Reviews','reviews.html'],['Open Calendar','bookings.html'],['Open Inbox','inbox.html'],['Open Clients','clients.html'],['Open Revenue','revenue.html'],['Open Lola','lola-live.html'],['Open Settings','settings.html']];let layer=null;function close(){layer?.remove();layer=null}function open(){if(layer)return;layer=document.createElement('div');layer.className='lola-command-layer show';layer.innerHTML=`<div class="lola-command"><div class="lola-command-input"><span>⌘</span><input autofocus placeholder="Go anywhere in LolaDesk…"></div><div class="lola-command-list"></div><div class="lola-command-foot">↑↓ navigate · Enter open · Esc close</div></div>`;document.body.appendChild(layer);const input=layer.querySelector('input'),list=layer.querySelector('.lola-command-list');let index=0,filtered=actions;function render(){list.innerHTML=filtered.map((a,i)=>`<button class="${i===index?'active':''}" data-i="${i}"><span>${escapeHtml(a[0])}</span><small>Open</small></button>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>location.href=filtered[+b.dataset.i][1])}input.oninput=()=>{filtered=actions.filter(a=>a[0].toLowerCase().includes(input.value.toLowerCase()));index=0;render()};input.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();index=Math.min(filtered.length-1,index+1);render()}if(e.key==='ArrowUp'){e.preventDefault();index=Math.max(0,index-1);render()}if(e.key==='Enter'&&filtered[index])location.href=filtered[index][1];if(e.key==='Escape')close()};layer.onclick=e=>{if(e.target===layer)close()};render();input.focus()}addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}})}
  document.addEventListener('DOMContentLoaded',()=>{ensure();connectivity();commandPalette();document.querySelectorAll('button,[role="button"],.btn').forEach(el=>el.addEventListener('pointerdown',()=>navigator.vibrate?.(8),{passive:true}))});
  window.LolaUX={toast,busy,run,confirm,skeleton,escapeHtml};
})();