name: Page audit
on:
  pull_request:
  push:
    branches: [main]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - run: npm ci --silent
      - run: npm run build
